# Generated by Django 4.2.7 on 2023-11-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("game_date", models.DateField()),
            ],
            options={"db_table": "game", "managed": False,},
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                ("score_id", models.AutoField(primary_key=True, serialize=False)),
                ("home_score", models.SmallIntegerField()),
                ("away_score", models.SmallIntegerField()),
                ("game_minute", models.SmallIntegerField()),
            ],
            options={"db_table": "score", "managed": False,},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team", models.CharField(max_length=50)),
            ],
            options={"db_table": "team", "managed": False,},
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("tournament_id", models.AutoField(primary_key=True, serialize=False)),
                ("tournament", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
            ],
            options={"db_table": "tournament", "managed": False,},
        ),
    ]
